#version 450

layout (local_size_x = 32) in;

layout(set = 0, binding = 0) writeonly buffer bout { float result[]; };
layout(set = 0, binding = 1) readonly  buffer bina { float in_a[]; };

void main() {
    //broadcasts input by duplicating
    //constant N is injected in python
    const uint N = {{N}};
    const uint out_index = gl_GlobalInvocationID.x;
    const uint in_index  = gl_GlobalInvocationID.x % N;
    result[out_index]    = in_a[in_index];
}