#version 450

layout (local_size_x = 1) in;

layout(set = 0, binding = 0) buffer bout { float result[]; };
layout(set = 0, binding = 1) buffer bina { float pred[]; };
layout(set = 0, binding = 2) buffer binb { float v0[]; };
layout(set = 0, binding = 3) buffer binc { float v1[]; };

void main() {
    const uint index = gl_GlobalInvocationID.x;
    result[index] = pred[index]*v0[index] + (1-pred[index])*v1[index];
}