#version 450

layout (local_size_x = 32) in;

layout(set = 0, binding = 0) writeonly buffer bout { float result[]; };
layout(set = 0, binding = 1) readonly  buffer bina { float pred[]; };
layout(set = 0, binding = 2) readonly  buffer binb { float v0[]; };
layout(set = 0, binding = 3) readonly  buffer binc { float v1[]; };

void main() {
    const uint index = gl_GlobalInvocationID.x;
    result[index] = pred[index]*v0[index] + (1-pred[index])*v1[index];
}