#version 450

layout (local_size_x = {{WORKGROUP_X}}) in;

layout(set = 0, binding = 0) readonly  buffer bina { uint in_a[]; };
layout(set = 0, binding = 1) readonly  buffer binb { uint in_b[]; };
layout(set = 0, binding = 2) writeonly buffer bout { uint result[]; };


void main() {
    const uint index     = gl_GlobalInvocationID.x; 
    result[index]        = in_a[index] >> min(in_b[index], 31);
}

