#version 450

layout (local_size_x = {{WORKGROUP_X}}) in;


layout(set = 0, binding = 0) writeonly buffer bout { float result[]; };
layout(set = 0, binding = 1) readonly  buffer bina { float in_a[]; };

void main() {
    //constants injected in python
    //in_a is a NxM matrix
    const uint N = {{N}};
    const uint M = {{M}};
    
    const uint index = gl_GlobalInvocationID.x;
    const uint row = index / N;
    const uint col = index % N;
    result[index] = in_a[col*M + row];
}
