#version 450

layout (local_size_x = 1) in;


layout(set = 0, binding = 0) buffer bout { float result[]; };
layout(set = 0, binding = 1) buffer bina { float in_a[]; };

void main() {
    //constants injected in python
    //in_a is a NxM matrix
    const uint N = {{N}};
    const uint M = {{M}};
    
    const uint index = gl_GlobalInvocationID.x;
    const uint row_a = index / N;
    const uint col_a = index % N;
    result[index] = in_a[col_a*N + row_a];
}
